### ISSUE TITLE
Software License, BSD like the Qt Examples?

### ISSUE THREAD

**Issue by WakeRealityDev** [WikiToLearn/WTL_client#1]
Hey, I didn't see you declare a license. is it BSD license like the Qt 5.9 examples code?  Thank you.

**Comment by hackertron** [comment]
yeah , the project is still in progress . I have not yet thought of proper license for it yet . I will discuss it with others . 

Thanks for pointing it out !!

**Comment by hackertron** [comment]
We have added GPL v3.0 license !!
